defaults:
  form_path: '/application-form'
  registration:
    from: 30.05.2016
    to: 09.06.2016
  reviewers:
    - idengager
    - gosiaciesla
    - agatasalska
    - bezmasla
    - kosmial
  registration_opens: "June 30th"
  registration_closes: "June 7th"
  review_starts: "June 8th"
  acceptance_emails: "June 10th"
